---
# sudo vi /etc/ansible/ansible.cfg , allow_world_readable_tmpfiles = True

- hosts: gogs
  vars_files:
  - postgres_vars.yml
  tasks:
  - name: update packages
    become: yes
    apt: "update_cache=yes"

  - name: postgres install
    become: yes
    apt: name={{item}} state=latest
    with_items:
     - "python-psycopg2"
     - "postgresql"
     - "postgresql-contrib"
 
  - name: check service status
    command: /usr/sbin/service postgresql status
    changed_when: false
 
  - name: update pg_hba.conf
    become: yes
    become_user: postgres
    vars:
     ansible_ssh_pipelining: true
    template:
     src: postgres_pg_hba_conf.j2
     dest: "{{postgres_config_path}}/pg_hba.conf"
     owner: postgres
     group: postgres
     mode: 0640
  
  - name: update postgresql.conf
    become: yes
    become_user: postgres
    lineinfile:
     path: "{{postgres_config_path}}/postgresql.conf"
     line: "listen_addresses = '*'"
  
  - name: restart postgres
    become: yes
    become_user: root
    command: /usr/sbin/service postgresql restart
  
  - name: create working database
    postgresql_db: name=gogs

  - name: create db user
    postgresql_user: db=gogs name=gogs expires=infinity priv="ALL"
    notify:
    - alter password

  handlers:
  - name: alter password
    become: yes
    become_user: postgres
    shell: psql -c "alter user gogs with password 'gogs'"

