---
- hosts: todeploy
  vars:
   os_user: "tudi"

  tasks:
  - name: download golang tarball
    become: yes
    get_url:
     url: 'https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz'
     dest: '/usr/local/src/go1.11.4.linux-amd64.tar.gz'

  - name: extract
    become: yes
    unarchive:
     copy: no
     dest: /usr/local
     src: '/usr/local/src/go1.11.4.linux-amd64.tar.gz'

  - name: folders for workspace
    become: yes
    file:
     path: "/home/{{os_user}}/{{item}}"
     group: "{{os_user}}"
     owner: "{{os_user}}"
     state: directory
     mode: 0755
    with_items:
     - 'go'
     - 'go/bin'
     - 'go/pkg'
     - 'go/src'

  - name: variables for workspace
    become: yes
    become_user: "{{os_user}}"
    lineinfile:
     create: yes
     dest: "/home/{{os_user}}/.bashrc"
     insertafter: EOF
     line: "{{item}}"
    with_items:
     - "export GOPATH=/home/{{os_user}}/go"
     - 'export PATH=$GOPATH/bin:$PATH'
     - 'export PATH=$PATH:/usr/local/go/bin'

  - name: url latest liteide
    local_action: 
     module: uri
     url: https://api.github.com/repos/visualfc/liteide/releases/latest
     return_content: yes
     method: GET
    register: json_info

  - name: download liteide
    become: yes
    become_user: "{{os_user}}"
    get_url:
     url: "{{json_info.json.assets[8].browser_download_url}}"
     dest: "/home/{{os_user}}/"

  - name: extract liteide
    become: yes
    become_user: "{{os_user}}"
    unarchive:
     copy: no
     dest: "/home/{{os_user}}/"
     src:  "/home/{{os_user}}/{{json_info.json.assets[8].name}}"
