---
- hosts: k8s-all
  become: yes
  remote_user: root
  tasks:

  - name: ping host
    ping:

  - name: timezone
    timezone: 
      name: Europe/Bucharest

  - name: relax security
    shell: |
      setenforce 0
      sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

  - name: relax firewall
    shell: |
      systemctl stop firewalld
      systemctl disable firewalld

  - name: Loading K8s required Kernel Module overlay
    community.general.modprobe:
      name: overlay
      state: present

  - name: Loading K8s required Kernel Module br_netfilter
    community.general.modprobe:
      name: br_netfilter
      state: present

  - name: enable bridging
    lineinfile: 
      path: /etc/sysctl.conf
      line: net.ipv4.ip_forward=1

  - name: Reload Kernel parameter configuration
    shell: |
      sysctl --system

  - name: disable swap
    shell: |
      swapoff -a
      sed -i 's/.*swap.*/#&/' /etc/fstab #   

  - name: add repo
    shell: |
      dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: prerequisites
    dnf: 
      name: 
        - containerd.io
      state: present 

  - name: generate containerd configuration
    shell: |
      mv /etc/containerd/config.toml /etc/containerd/config.toml.orig
      containerd config default > /etc/containerd/config.toml

  - name: set SystemdCgroup = true
    ansible.builtin.lineinfile:
     path: /etc/containerd/config.toml
     regexp: '^systemd_cgroup='
     line: systemd_cgroup = true

  - name: Enable and start Containerd service
    shell: |
      systemctl enable --now containerd.service
