---
- hosts: k8sall
  become: yes
  remote_user: root
  gather_facts: false
  
  vars:
    dnsEntries: "\n192.168.1.55 k8s-master\n192.168.1.56 k8s-node1\n192.168.1.57 k8s-node2\n\n" 
    kernelModules: "overlay\nbr_netfilter\n"
    networkBridge: "net.bridge.bridge-nf-call-iptables = 1\nnet.ipv4.ip_forward = 1\nnet.bridge.bridge-nf-call-ip6tables = 1\n"
  
  tasks:
  - name: ping host
    ping:

  - name: timezone
    timezone: 
      name: Europe/Bucharest

  - name: prerequisites
    apt:
      name:
        - qemu-guest-agent
        - mc    
        - curl
        - gnupg2
        - software-properties-common
        - apt-transport-https
        - ca-certificates 
      state: present

  - name: /etc/hosts
    blockinfile: 
      path: /etc/hosts
      block: "{{dnsEntries}}"

  - name: /etc/modules
    blockinfile: 
      path: /etc/modules-load.d/containerd.conf
      block: "{{kernelModules}}"

  - name: /etc/sysctl.d/99-kubernetes-cri.conf
    blockinfile: 
      path: /etc/sysctl.d/99-kubernetes-cri.conf
      block: "{{networkBridge}}"

  - name: disable swap
    shell: |
      swapoff -a
      sed -i 's/.*swap.*/#&/' /etc/fstab #   

  # - name: uninstall the installed Docker
  #   apt: 
  #     name:
  #      - docker-ce
  #      - docker-ce-cli
  #      - containerd.io
  #     state: absent   

  - name: configurations
    shell: |
      modprobe overlay
      modprobe br_netfilter
      sysctl --system

  - name: Add Docker GPG apt Key
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
 
  - name: add Docker software source
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu jammy stable
     state: present

  - name: containerd install
    apt:
      name:
        - containerd.io
      state: present

  - name: containerd enable 
    shell: |
      systemctl restart containerd
      systemctl enable containerd
      containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1
      sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

  - name: add K8s key and repo
    shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.26/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.26/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list


  - name: install K8s
    shell: |
          sudo apt-get update
          sudo apt-get install -y kubelet=1.26.8-1.1 kubeadm=1.26.8-1.1 kubectl=1.26.8-1.1
          sudo apt-mark hold kubelet kubeadm kubectl
