version: '3.7'

services:
  server:
    image: gitea/gitea:1.13.6
    container_name: gitea
    environment:
      - ROOT_URL=http://172.30.0.5:3000
      - APP_NAME="GITEA"
      - RUN_MODE="prod"
      - DISABLE_REGISTRATION=true
      - USER_UID=1000
      - USER_GID=1000
    restart: always
#    volumes:
#      - ./gitea:/data
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:3000"
      - "8822:22"
    networks:
      gitea:
       ipv4_address: 172.30.0.5


  plantuml:
    image: 'plantuml/plantuml-server:tomcat'
    container_name: plantuml
    
    ports:
      - "8000:8080"
    networks:
      gitea:
       ipv4_address: 172.30.0.6


  drone-server:
    image: drone/drone:1.2.1
    container_name: drone-server
    ports:
      - 80:80
      - 9000
    restart: always
    depends_on:
      - server
    environment:
      - DRONE_OPEN=true
      - DRONE_GITEA=true
      - DRONE_NETWORK=gitea
      - DRONE_DEBUG=true
      - DRONE_ADMIN=tudi
      - DRONE_USER_CREATE=username:tudi,admin:true
      - DRONE_SERVER_PORT=:80
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA_SERVER=http://172.30.0.5:3000
      - DRONE_RPC_SECRET=9c3921e3e748aff725d2e16ef31fbc42
      - DRONE_SERVER_HOST=drone-server:80
      - DRONE_HOST=http://drone-server:80
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
    networks:
      gitea:
       ipv4_address: 172.30.0.7

  drone-agent:
    image: drone/agent:1.2.1
    container_name: drone-agent
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=http://drone-server:80
      - DRONE_RPC_SECRET=9c3921e3e748aff725d2e16ef31fbc42
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_RUNNER_NETWORKS=gitea
    networks:
      gitea:
       ipv4_address: 172.30.0.9
      
networks:
  gitea:
   name: gitea
   ipam:
     driver: default
     config:
       - subnet: "172.30.0.0/24"
