---
- hosts: wordpress
  become: yes
  tasks:
  - name: update packages 
    apt: update_cache=yes

  - name: Ubuntu install - prerequisites1
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Ubuntu install - prerequisites2 
    apt: 
      pkg:
       - apache2
       - php
       - libapache2-mod-php
       - php-mysql
       - php-xml
       - php-curl
       - php-gd
       - php-zip
       - php-imagick
       - php-mbstring
       - vsftpd
       - openssl

  - name: enable Apache ssl module
    apache2_module: 
      name: ssl
      state: present

  
